[build]
  base = "/"
  publish = "public" 
  command = "npm i"


[build.environment]
  NODE_ENV = "production"


[context.production]
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
